In [24]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [25]:
a = ((2*np.ones(20))**np.arange(1, 21))/np.arange(1, 21)
a

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [26]:
b = ((0.1**(3*np.arange(6)))*(0.2**(4*np.arange(6)))).sum()
b

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [27]:
def pattern(i, j):
  return np.where((i+j)%2 == 0, 1, 0)

res = np.fromfunction(pattern, (8, 8))
res

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [28]:
X = np.random.random((5, 2))

p = np.sqrt(X[:, 0]**2+X[:, 1]**2)
f = np.arccos(X[:, 0]/p)
Y = np.vstack((p, f)).T
Y

array([[0.75050007, 1.54594594],
       [1.04436195, 0.49837889],
       [0.88812863, 0.26349151],
       [1.00948087, 0.5837992 ],
       [0.75776211, 0.70727888]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [29]:
X = np.random.random((10, 10))

ind = np.argmax(X)
d = (ind//10, ind -(ind//10)*10)
d

(8, 8)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [30]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
res = np.argmax(((X - y)**2).sum(axis=1))
X[res]

array([0.67725474, 0.90630433])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [31]:
x1, x2, x3 = np.arange(-3, 0, 0.2), np.arange(0, 2.1, 0.2), np.arange(2, 0, 3.1)
f = np.hstack(((x1**2 + 2*x1) + 6, x2 + 6, x3**2 + 4*x3 -4))
f

array([9.  , 8.24, 7.56, 6.96, 6.44, 6.  , 5.64, 5.36, 5.16, 5.04, 5.  ,
       5.04, 5.16, 5.36, 5.64, 6.  , 6.2 , 6.4 , 6.6 , 6.8 , 7.  , 7.2 ,
       7.4 , 7.6 , 7.8 , 8.  ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [32]:
X = np.random.random((10, 10))

X = X - X.mean(axis=1).reshape(10, 1)
X.mean(axis=1)

array([-1.33226763e-16,  4.44089210e-17, -4.44089210e-17,  0.00000000e+00,
       -7.77156117e-17,  0.00000000e+00,  0.00000000e+00,  6.66133815e-17,
       -2.22044605e-17, -2.22044605e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [33]:
X = np.random.normal(loc=5, scale=2., size=1000)

m = X.sum()/len(X)
d = ((X-m)**2).sum() / len(X)
print(m)
print(d)

4.982739954909444
4.038899180086402


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [34]:
def pattern(i, j):
  return np.where((i+j-5) >= 0, i + j - 5, i + j)

res = np.fromfunction(pattern, (5, 5))
res

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [35]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        print(val)
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

50.3956838543417
62.96842625054355
25.76233410666655
48.06204220076495
56.540344030886175


[1, 4, 0, 0, 3]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [36]:
def fast_sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    val = s*np.random.random(c)
    print(val)
    val = val.reshape((c, 1))
    x = np.array(x).cumsum().reshape((1, c))
    res = (x < val).astype('int')
    return res.sum(axis=1)

fast_sample([50, 3, 1, 7, 20], 5)

[53.77804741 72.51603423  4.93138456 33.71974001 37.15090197]


array([2, 4, 0, 0, 0])